package utils;

import java.awt.Color;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.HashMap;

/**
 * Java Code to get a color name from rgb/hex value/awt color
 *
 * The part of looking up a color name from the rgb values is edited from
 * https://gist.github.com/nightlark/6482130#file-gistfile1-java (that has some
 * errors) by Ryan Mast (nightlark)
 *
 * @author Xiaoxiao Li
 *
 */
public class ColorUtils {

    private static HashMap<String, String> map = new HashMap<>();

    static {
        map.put("Elipse", "66FFFF");
        map.put("Acid green", "B0BF1A");
        map.put("Aero", "7CB9E8");
        map.put("Aero blue", "C9FFE5");
        map.put("African violet", "B284BE");
        map.put("Air Force blue (RAF)", "5D8AA8");
        map.put("Air Force blue (USAF)", "00308F");
        map.put("Air superiority blue", "72A0C1");
        map.put("Alabama crimson", "AF002A");
        map.put("Alice blue", "F0F8FF");
        map.put("Alizarin crimson", "E32636");
        map.put("Alloy orange", "C46210");
        map.put("Almond", "EFDECD");
        map.put("Amaranth", "E52B50");
        map.put("Amaranth deep purple", "AB274F");
        map.put("Amaranth pink", "F19CBB");
        map.put("Amaranth purple", "AB274F");
        map.put("Amaranth red", "D3212D");
        map.put("Amazon", "3B7A57");
        map.put("Amber", "FFBF00");
        map.put("Amber (SAE/ECE)", "FF7E00");
        map.put("American rose", "FF033E");
        map.put("Amethyst", "9966CC");
        map.put("Android green", "A4C639");
        map.put("Anti-flash white", "F2F3F4");
        map.put("Antique brass", "CD9575");
        map.put("Antique bronze", "665D1E");
        map.put("Antique fuchsia", "915C83");
        map.put("Antique ruby", "841B2D");
        map.put("Antique white", "FAEBD7");
        map.put("Ao (English)", "008000");
        map.put("Apple green", "8DB600");
        map.put("Apricot", "FBCEB1");
        map.put("Aqua", "00FFFF");
        map.put("Aquamarine", "7FFFD4");
        map.put("Army green", "4B5320");
        map.put("Arsenic", "3B444B");
        map.put("Artichoke", "8F9779");
        map.put("Arylide yellow", "E9D66B");
        map.put("Ash grey", "B2BEB5");
        map.put("Asparagus", "87A96B");
        map.put("Atomic tangerine", "FF9966");
        map.put("Auburn", "A52A2A");
        map.put("Aureolin", "FDEE00");
        map.put("AuroMetalSaurus", "6E7F80");
        map.put("Avocado", "568203");
        map.put("Azure", "007FFF");
        map.put("Azure (web color)", "F0FFFF");
        map.put("Azure mist", "F0FFFF");
        map.put("Azureish white", "DBE9F4");
        map.put("B'dazzled blue", "2E5894");
        map.put("Baby blue", "89CFF0");
        map.put("Baby blue eyes", "A1CAF1");
        map.put("Baby pink", "F4C2C2");
        map.put("Baby powder", "FEFEFA");
        map.put("Baker-Miller pink", "FF91AF");
        map.put("Ball blue", "21ABCD");
        map.put("Banana Mania", "FAE7B5");
        map.put("Banana yellow", "FFE135");
        map.put("Bangladesh green", "006A4E");
        map.put("Barbie pink", "E0218A");
        map.put("Barn red", "7C0A02");
        map.put("Battleship grey", "848482");
        map.put("Bazaar", "98777B");
        map.put("Beau blue", "BCD4E6");
        map.put("Beaver", "9F8170");
        map.put("Beige", "F5F5DC");
        map.put("Big dip o’ruby", "9C2542");
        map.put("Bisque", "FFE4C4");
        map.put("Bistre", "3D2B1F");
        map.put("Bistre brown", "967117");
        map.put("Bitter lemon", "CAE00D");
        map.put("Bitter lime", "BFFF00");
        map.put("Bittersweet", "FE6F5E");
        map.put("Bittersweet shimmer", "BF4F51");
        map.put("Black", "000000");
        map.put("Black bean", "3D0C02");
        map.put("Black leather jacket", "253529");
        map.put("Black olive", "3B3C36");
        map.put("Blanched almond", "FFEBCD");
        map.put("Blast-off bronze", "A57164");
        map.put("Bleu de France", "318CE7");
        map.put("Blizzard Blue", "ACE5EE");
        map.put("Blond", "FAF0BE");
        map.put("Blue", "0000FF");
        map.put("Blue (Crayola)", "1F75FE");
        map.put("Blue (Munsell)", "0093AF");
        map.put("Blue (NCS)", "0087BD");
        map.put("Blue (Pantone)", "0018A8");
        map.put("Blue (pigment)", "333399");
        map.put("Blue (RYB)", "0247FE");
        map.put("Blue Bell", "A2A2D0");
        map.put("Blue Lagoon", "5E93A1");
        map.put("Blue sapphire", "126180");
        map.put("Blue yonder", "5072A7");
        map.put("Blue-gray", "6699CC");
        map.put("Blue-green", "0D98BA");
        map.put("Blue-magenta violet", "553592");
        map.put("Blue-violet", "8A2BE2");
        map.put("Blueberry", "4F86F7");
        map.put("Bluebonnet", "1C1CF0");
        map.put("Blush", "DE5D83");
        map.put("Bole", "79443B");
        map.put("Bondi blue", "0095B6");
        map.put("Bone", "E3DAC9");
        map.put("Boston University Red", "CC0000");
        map.put("Bottle green", "006A4E");
        map.put("Boysenberry", "873260");
        map.put("Brandeis blue", "0070FF");
        map.put("Brass", "B5A642");
        map.put("Brick red", "CB4154");
        map.put("Bright cerulean", "1DACD6");
        map.put("Bright green", "66FF00");
        map.put("Bright lavender", "BF94E4");
        map.put("Bright lilac", "D891EF");
        map.put("Bright maroon", "C32148");
        map.put("Bright navy blue", "1974D2");
        map.put("Bright pink", "FF007F");
        map.put("Bright turquoise", "08E8DE");
        map.put("Bright ube", "D19FE8");
        map.put("Brilliant azure", "3399FF");
        map.put("Brilliant lavender", "F4BBFF");
        map.put("Brilliant rose", "FF55A3");
        map.put("Brink pink", "FB607F");
        map.put("British racing green", "004225");
        map.put("Bronze", "CD7F32");
        map.put("Bronze Yellow", "737000");
        map.put("Brown (traditional)", "964B00");
        map.put("Brown (web)", "A52A2A");
        map.put("Brown Yellow", "cc9966");
        map.put("Brown-nose", "6B4423");
        map.put("Brunswick green", "1B4D3E");
        map.put("Bubble gum", "FFC1CC");
        map.put("Bubbles", "E7FEFF");
        map.put("Bud green", "7BB661");
        map.put("Buff", "F0DC82");
        map.put("Bulgarian rose", "480607");
        map.put("Burgundy", "800020");
        map.put("Burlywood", "DEB887");
        map.put("Burnt orange", "CC5500");
        map.put("Burnt sienna", "E97451");
        map.put("Burnt umber", "8A3324");
        map.put("Byzantine", "BD33A4");
        map.put("Byzantium", "702963");
        map.put("Cadet", "536872");
        map.put("Cadet blue", "5F9EA0");
        map.put("Cadet grey", "91A3B0");
        map.put("Cadmium green", "006B3C");
        map.put("Cadmium orange", "ED872D");
        map.put("Cadmium red", "E30022");
        map.put("Cadmium yellow", "FFF600");
        map.put("Café au lait", "A67B5B");
        map.put("Café noir", "4B3621");
        map.put("Cal Poly green", "1E4D2B");
        map.put("Cambridge Blue", "A3C1AD");
        map.put("Camel", "C19A6B");
        map.put("Cameo pink", "EFBBCC");
        map.put("Camouflage green", "78866B");
        map.put("Canary yellow", "FFEF00");
        map.put("Candy apple red", "FF0800");
        map.put("Candy pink", "E4717A");
        map.put("Capri", "00BFFF");
        map.put("Caput mortuum", "592720");
        map.put("Cardinal", "C41E3A");
        map.put("Caribbean green", "00CC99");
        map.put("Carmine", "960018");
        map.put("Carmine (M&P)", "D70040");
        map.put("Carmine pink", "EB4C42");
        map.put("Carmine red", "FF0038");
        map.put("Carnation pink", "FFA6C9");
        map.put("Carnelian", "B31B1B");
        map.put("Carolina blue", "56A0D3");
        map.put("Carrot orange", "ED9121");
        map.put("Castleton green", "00563F");
        map.put("Catalina blue", "062A78");
        map.put("Catawba", "703642");
        map.put("Cedar Chest", "C95A49");
        map.put("Ceil", "92A1CF");
        map.put("Celadon", "ACE1AF");
        map.put("Celadon blue", "007BA7");
        map.put("Celadon green", "2F847C");
        map.put("Celeste", "B2FFFF");
        map.put("Celestial blue", "4997D0");
        map.put("Cerise", "DE3163");
        map.put("Cerise pink", "EC3B83");
        map.put("Cerulean", "007BA7");
        map.put("Cerulean blue", "2A52BE");
        map.put("Cerulean frost", "6D9BC3");
        map.put("CG Blue", "007AA5");
        map.put("CG Red", "E03C31");
        map.put("Chamoisee", "A0785A");
        map.put("Champagne", "F7E7CE");
        map.put("Charcoal", "36454F");
        map.put("Charleston green", "232B2B");
        map.put("Charm pink", "E68FAC");
        map.put("Chartreuse (traditional)", "DFFF00");
        map.put("Chartreuse (web)", "7FFF00");
        map.put("Cherry", "DE3163");
        map.put("Cherry blossom pink", "FFB7C5");
        map.put("Chestnut", "954535");
        map.put("China pink", "DE6FA1");
        map.put("China rose", "A8516E");
        map.put("Chinese red", "AA381E");
        map.put("Chinese violet", "856088");
        map.put("Chocolate (traditional)", "7B3F00");
        map.put("Chocolate (web)", "D2691E");
        map.put("Chrome yellow", "FFA700");
        map.put("Cinereous", "98817B");
        map.put("Cinnabar", "E34234");
        map.put("Cinnamon[citation needed]", "D2691E");
        map.put("Citrine", "E4D00A");
        map.put("Citron", "9FA91F");
        map.put("Claret", "7F1734");
        map.put("Classic rose", "FBCCE7");
        map.put("Cobalt Blue", "0047AB");
        map.put("Cocoa brown", "D2691E");
        map.put("Coconut", "965A3E");
        map.put("Coffee", "6F4E37");
        map.put("Columbia Blue", "C4D8E2");
        map.put("Congo pink", "F88379");
        map.put("Cool Black", "002E63");
        map.put("Cool Grey", "8C92AC");
        map.put("Copper", "B87333");
        map.put("Copper (Crayola)", "DA8A67");
        map.put("Copper penny", "AD6F69");
        map.put("Copper red", "CB6D51");
        map.put("Copper rose", "996666");
        map.put("Coquelicot", "FF3800");
        map.put("Coral", "FF7F50");
        map.put("Coral pink", "F88379");
        map.put("Coral red", "FF4040");
        map.put("Cordovan", "893F45");
        map.put("Corn", "FBEC5D");
        map.put("Cornell Red", "B31B1B");
        map.put("Cornflower blue", "6495ED");
        map.put("Cornsilk", "FFF8DC");
        map.put("Cosmic latte", "FFF8E7");
        map.put("Cotton candy", "FFBCD9");
        map.put("Coyote brown", "81613e");
        map.put("Cream", "FFFDD0");
        map.put("Crimson", "DC143C");
        map.put("Crimson glory", "BE0032");
        map.put("Crimson red", "990000");
        map.put("Cyan", "00FFFF");
        map.put("Cyan (process)", "00B7EB");
        map.put("Cyan azure", "4E82b4");
        map.put("Cyan cobalt blue", "28589C");
        map.put("Cyan cornflower blue", "188BC2");
        map.put("Cyan-blue azure", "4682BF");
        map.put("Cyber grape", "58427C");
        map.put("Cyber yellow", "FFD300");
        map.put("Daffodil", "FFFF31");
        map.put("Dandelion", "F0E130");
        map.put("Dark blue", "00008B");
        map.put("Dark blue-gray", "666699");
        map.put("Dark brown", "654321");
        map.put("Dark brown-tangelo", "88654E");
        map.put("Dark byzantium", "5D3954");
        map.put("Dark candy apple red", "A40000");
        map.put("Dark cerulean", "08457E");
        map.put("Dark chestnut", "986960");
        map.put("Dark coral", "CD5B45");
        map.put("Dark cyan", "008B8B");
        map.put("Dark electric blue", "536878");
        map.put("Dark goldenrod", "B8860B");
        map.put("Dark gray (X11)", "A9A9A9");
        map.put("Dark green", "013220");
        map.put("Dark green (X11)", "006400");
        map.put("Dark imperial blue", "00416A");
        map.put("Dark imperial blue", "6E6EF9");
        map.put("Dark jungle green", "1A2421");
        map.put("Dark khaki", "BDB76B");
        map.put("Dark lava", "483C32");
        map.put("Dark lavender", "734F96");
        map.put("Dark liver", "534B4F");
        map.put("Dark liver (horses)", "543D37");
        map.put("Dark magenta", "8B008B");
        map.put("Dark medium gray", "A9A9A9");
        map.put("Dark midnight blue", "003366");
        map.put("Dark moss green", "4A5D23");
        map.put("Dark olive green", "556B2F");
        map.put("Dark orange", "FF8C00");
        map.put("Dark orchid", "9932CC");
        map.put("Dark pastel blue", "779ECB");
        map.put("Dark pastel green", "03C03C");
        map.put("Dark pastel purple", "966FD6");
        map.put("Dark pastel red", "C23B22");
        map.put("Dark pink", "E75480");
        map.put("Dark powder blue", "003399");
        map.put("Dark puce", "4F3A3C");
        map.put("Dark purple", "301934");
        map.put("Dark raspberry", "872657");
        map.put("Dark red", "8B0000");
        map.put("Dark salmon", "E9967A");
        map.put("Dark scarlet", "560319");
        map.put("Dark sea green", "8FBC8F");
        map.put("Dark sienna", "3C1414");
        map.put("Dark sky blue", "8CBED6");
        map.put("Dark slate blue", "483D8B");
        map.put("Dark slate gray", "2F4F4F");
        map.put("Dark spring green", "177245");
        map.put("Dark tan", "918151");
        map.put("Dark tangerine", "FFA812");
        map.put("Dark taupe", "483C32");
        map.put("Dark terra cotta", "CC4E5C");
        map.put("Dark turquoise", "00CED1");
        map.put("Dark vanilla", "D1BEA8");
        map.put("Dark violet", "9400D3");
        map.put("Dark yellow", "9B870C");
        map.put("Dartmouth green", "00703C");
        map.put("Davy's grey", "555555");
        map.put("Debian red", "D70A53");
        map.put("Deep aquamarine", "40826D");
        map.put("Deep carmine", "A9203E");
        map.put("Deep carmine pink", "EF3038");
        map.put("Deep carrot orange", "E9692C");
        map.put("Deep cerise", "DA3287");
        map.put("Deep champagne", "FAD6A5");
        map.put("Deep chestnut", "B94E48");
        map.put("Deep coffee", "704241");
        map.put("Deep fuchsia", "C154C1");
        map.put("Deep Green", "056608");
        map.put("Deep green-cyan turquoise", "0E7C61");
        map.put("Deep jungle green", "004B49");
        map.put("Deep koamaru", "333366");
        map.put("Deep lemon", "F5C71A");
        map.put("Deep lilac", "9955BB");
        map.put("Deep magenta", "CC00CC");
        map.put("Deep maroon", "820000");
        map.put("Deep mauve", "D473D4");
        map.put("Deep moss green", "355E3B");
        map.put("Deep peach", "FFCBA4");
        map.put("Deep pink", "FF1493");
        map.put("Deep puce", "A95C68");
        map.put("Deep Red", "850101");
        map.put("Deep ruby", "843F5B");
        map.put("Deep saffron", "FF9933");
        map.put("Deep sky blue", "00BFFF");
        map.put("Deep Space Sparkle", "4A646C");
        map.put("Deep spring bud", "556B2F");
        map.put("Deep Taupe", "7E5E60");
        map.put("Deep Tuscan red", "66424D");
        map.put("Deep violet", "330066");
        map.put("Deer", "BA8759");
        map.put("Denim", "1560BD");
        map.put("Desaturated cyan", "669999");
        map.put("Desert", "C19A6B");
        map.put("Desert sand", "EDC9AF");
        map.put("Desire", "EA3C53");
        map.put("Diamond", "B9F2FF");
        map.put("Dim gray", "696969");
        map.put("Dirt", "9B7653");
        map.put("Dodger blue", "1E90FF");
        map.put("Dogwood rose", "D71868");
        map.put("Dollar bill", "85BB65");
        map.put("Donkey brown", "664C28");
        map.put("Drab", "967117");
        map.put("Duke blue", "00009C");
        map.put("Dust storm", "E5CCC9");
        map.put("Dutch white", "EFDFBB");
        map.put("Earth yellow", "E1A95F");
        map.put("Ebony", "555D50");
        map.put("Ecru", "C2B280");
        map.put("Eerie black", "1B1B1B");
        map.put("Eggplant", "614051");
        map.put("Eggshell", "F0EAD6");
        map.put("Egyptian blue", "1034A6");
        map.put("Electric blue", "7DF9FF");
        map.put("Electric crimson", "FF003F");
        map.put("Electric cyan", "00FFFF");
        map.put("Electric green", "00FF00");
        map.put("Electric indigo", "6F00FF");
        map.put("Electric lavender", "F4BBFF");
        map.put("Electric lime", "CCFF00");
        map.put("Electric purple", "BF00FF");
        map.put("Electric ultramarine", "3F00FF");
        map.put("Electric violet", "8F00FF");
        map.put("Electric yellow", "FFFF33");
        map.put("Emerald", "50C878");
        map.put("Eminence", "6C3082");
        map.put("English green", "1B4D3E");
        map.put("English lavender", "B48395");
        map.put("English red", "AB4B52");
        map.put("English violet", "563C5C");
        map.put("Eton blue", "96C8A2");
        map.put("Eucalyptus", "44D7A8");
        map.put("Fallow", "C19A6B");
        map.put("Falu red", "801818");
        map.put("Fandango", "B53389");
        map.put("Fandango pink", "DE5285");
        map.put("Fashion fuchsia", "F400A1");
        map.put("Fawn", "E5AA70");
        map.put("Feldgrau", "4D5D53");
        map.put("Feldspar", "FDD5B1");
        map.put("Fern green", "4F7942");
        map.put("Ferrari Red", "FF2800");
        map.put("Field drab", "6C541E");
        map.put("Fire engine red", "CE2029");
        map.put("Firebrick", "B22222");
        map.put("Flame", "E25822");
        map.put("Flamingo pink", "FC8EAC");
        map.put("Flattery", "6B4423");
        map.put("Flavescent", "F7E98E");
        map.put("Flax", "EEDC82");
        map.put("Flirt", "A2006D");
        map.put("Floral white", "FFFAF0");
        map.put("Fluorescent orange", "FFBF00");
        map.put("Fluorescent pink", "FF1493");
        map.put("Fluorescent yellow", "CCFF00");
        map.put("Folly", "FF004F");
        map.put("Forest green (traditional)", "014421");
        map.put("Forest green (web)", "228B22");
        map.put("French beige", "A67B5B");
        map.put("French bistre", "856D4D");
        map.put("French blue", "0072BB");
        map.put("French fuchsia", "FD3F92");
        map.put("French lilac", "86608E");
        map.put("French lime", "9EFD38");
        map.put("French mauve", "D473D4");
        map.put("French pink", "FD6C9E");
        map.put("French plum", "811453");
        map.put("French puce", "4E1609");
        map.put("French raspberry", "C72C48");
        map.put("French rose", "F64A8A");
        map.put("French sky blue", "77B5FE");
        map.put("French violet", "8806CE");
        map.put("French wine", "AC1E44");
        map.put("Fresh Air", "A6E7FF");
        map.put("Fuchsia", "FF00FF");
        map.put("Fuchsia (Crayola)", "C154C1");
        map.put("Fuchsia pink", "FF77FF");
        map.put("Fuchsia purple", "CC397B");
        map.put("Fuchsia rose", "C74375");
        map.put("Fulvous", "E48400");
        map.put("Fuzzy Wuzzy", "CC6666");
        map.put("Gainsboro", "DCDCDC");
        map.put("Gamboge", "E49B0F");
        map.put("Gamboge orange (brown)", "996600");
        map.put("Generic viridian", "007F66");
        map.put("Ghost white", "F8F8FF");
        map.put("Giants orange", "FE5A1D");
        map.put("Grussrel", "B06500");
        map.put("Glaucous", "6082B6");
        map.put("Glitter", "E6E8FA");
        map.put("GO green", "00AB66");
        map.put("Gold (metallic)", "D4AF37");
        map.put("Gold (web) (Golden)", "FFD700");
        map.put("Gold Fusion", "85754E");
        map.put("Golden brown", "996515");
        map.put("Golden poppy", "FCC200");
        map.put("Golden yellow", "FFDF00");
        map.put("Goldenrod", "DAA520");
        map.put("Granny Smith Apple", "A8E4A0");
        map.put("Grape", "6F2DA8");
        map.put("Gray", "808080");
        map.put("Gray (HTML/CSS gray)", "808080");
        map.put("Gray (X11 gray)", "BEBEBE");
        map.put("Gray-asparagus", "465945");
        map.put("Gray-blue", "8C92AC");
        map.put("Green (Color Wheel) (X11 green)", "00FF00");
        map.put("Green (Crayola)", "1CAC78");
        map.put("Green (HTML/CSS color)", "008000");
        map.put("Green (Munsell)", "00A877");
        map.put("Green (NCS)", "009F6B");
        map.put("Green (Pantone)", "00AD43");
        map.put("Green (pigment)", "00A550");
        map.put("Green (RYB)", "66B032");
        map.put("Green-blue", "1164B4");
        map.put("Green-cyan", "009966");
        map.put("Green-yellow", "ADFF2F");
        map.put("Grizzly", "885818");
        map.put("Grullo", "A99A86");
        map.put("Guppie green", "00FF7F");
        map.put("Halayà úbe", "663854");
        map.put("Han blue", "446CCF");
        map.put("Han purple", "5218FA");
        map.put("Hansa yellow", "E9D66B");
        map.put("Harlequin", "3FFF00");
        map.put("Harlequin green", "46CB18");
        map.put("Harvard crimson", "C90016");
        map.put("Harvest gold", "DA9100");
        map.put("Heart Gold", "808000");
        map.put("Heliotrope", "DF73FF");
        map.put("Heliotrope gray", "AA98A9");
        map.put("Heliotrope magenta", "AA00BB");
        map.put("Hollywood cerise", "F400A1");
        map.put("Honeydew", "F0FFF0");
        map.put("Honolulu blue", "006DB0");
        map.put("Hooker's green", "49796B");
        map.put("Hot magenta", "FF1DCE");
        map.put("Hot pink", "FF69B4");
        map.put("Hunter green", "355E3B");
        map.put("Iceberg", "71A6D2");
        map.put("Icterine", "FCF75E");
        map.put("Illuminating Emerald", "319177");
        map.put("Imperial", "602F6B");
        map.put("Imperial blue", "002395");
        map.put("Imperial purple", "66023C");
        map.put("Imperial red", "ED2939");
        map.put("Inchworm", "B2EC5D");
        map.put("Independence", "4C516D");
        map.put("India green", "138808");
        map.put("Indian red", "CD5C5C");
        map.put("Indian yellow", "E3A857");
        map.put("Indigo", "6F00FF");
        map.put("Indigo dye", "091F92");
        map.put("Indigo (web)", "4B0082");
        map.put("International Klein Blue", "002FA7");
        map.put("International orange (aerospace)", "FF4F00");
        map.put("International orange (engineering)", "BA160C");
        map.put("International orange (Golden Gate Bridge)", "C0362C");
        map.put("Iris", "5A4FCF");
        map.put("Irresistible", "B3446C");
        map.put("Isabelline", "F4F0EC");
        map.put("Islamic green", "009000");
        map.put("Italian sky blue", "B2FFFF");
        map.put("Ivory", "FFFFF0");
        map.put("Jade", "00A86B");
        map.put("Japanese carmine", "9D2933");
        map.put("Japanese indigo", "264348");
        map.put("Japanese violet", "5B3256");
        map.put("Jasmine", "F8DE7E");
        map.put("Jasper", "D73B3E");
        map.put("Jazzberry jam", "A50B5E");
        map.put("Jelly Bean", "DA614E");
        map.put("Jet", "343434");
        map.put("Jonquil", "F4CA16");
        map.put("Jordy blue", "8AB9F1");
        map.put("June bud", "BDDA57");
        map.put("Jungle green", "29AB87");
        map.put("Kelly green", "4CBB17");
        map.put("Kenyan copper", "7C1C05");
        map.put("Keppel", "3AB09E");
        map.put("Jawad/Chicken Color (HTML/CSS) (Khaki)", "C3B091");
        map.put("Khaki (X11) (Light khaki)", "F0E68C");
        map.put("Kobe", "882D17");
        map.put("Kobi", "E79FC4");
        map.put("Kombu green", "354230");
        map.put("KU Crimson", "E8000D");
        map.put("La Salle Green", "087830");
        map.put("Languid lavender", "D6CADD");
        map.put("Lapis lazuli", "26619C");
        map.put("Laser Lemon", "FFFF66");
        map.put("Laurel green", "A9BA9D");
        map.put("Lava", "CF1020");
        map.put("Lavender (floral)", "B57EDC");
        map.put("Lavender (web)", "E6E6FA");
        map.put("Lavender blue", "CCCCFF");
        map.put("Lavender blush", "FFF0F5");
        map.put("Lavender gray", "C4C3D0");
        map.put("Lavender indigo", "9457EB");
        map.put("Lavender magenta", "EE82EE");
        map.put("Lavender mist", "E6E6FA");
        map.put("Lavender pink", "FBAED2");
        map.put("Lavender purple", "967BB6");
        map.put("Lavender rose", "FBA0E3");
        map.put("Lawn green", "7CFC00");
        map.put("Lemon", "FFF700");
        map.put("Lemon chiffon", "FFFACD");
        map.put("Lemon curry", "CCA01D");
        map.put("Lemon glacier", "FDFF00");
        map.put("Lemon lime", "E3FF00");
        map.put("Lemon meringue", "F6EABE");
        map.put("Lemon yellow", "FFF44F");
        map.put("Lenurple", "BA93D8");
        map.put("Licorice", "1A1110");
        map.put("Liberty", "545AA7");
        map.put("Light apricot", "FDD5B1");
        map.put("Light blue", "ADD8E6");
        map.put("Light brilliant red", "fe2e2e");
        map.put("Light brown", "B5651D");
        map.put("Light carmine pink", "E66771");
        map.put("Light cobalt blue", "88ACE0");
        map.put("Light coral", "F08080");
        map.put("Light cornflower blue", "93CCEA");
        map.put("Light crimson", "F56991");
        map.put("Light cyan", "E0FFFF");
        map.put("Light deep pink", "FF5CCD");
        map.put("Light French beige", "C8AD7F");
        map.put("Light fuchsia pink", "F984EF");
        map.put("Light goldenrod yellow", "FAFAD2");
        map.put("Light gray", "D3D3D3");
        map.put("Light grayish magenta", "CC99CC");
        map.put("Light green", "90EE90");
        map.put("Light hot pink", "FFB3DE");
        map.put("Light khaki", "F0E68C");
        map.put("Light medium orchid", "D39BCB");
        map.put("Light moss green", "ADDFAD");
        map.put("Light orchid", "E6A8D7");
        map.put("Light pastel purple", "B19CD9");
        map.put("Light pink", "FFB6C1");
        map.put("Light red ochre", "E97451");
        map.put("Light salmon", "FFA07A");
        map.put("Light salmon pink", "FF9999");
        map.put("Light sea green", "20B2AA");
        map.put("Light sky blue", "87CEFA");
        map.put("Light slate gray", "778899");
        map.put("Light steel blue", "B0C4DE");
        map.put("Light taupe", "B38B6D");
        map.put("Light Thulian pink", "E68FAC");
        map.put("Light yellow", "FFFFE0");
        map.put("Lilac", "C8A2C8");
        map.put("Lime (color wheel)", "BFFF00");
        map.put("Lime (web) (X11 green)", "00FF00");
        map.put("Lime green", "32CD32");
        map.put("Limerick", "9DC209");
        map.put("Lincoln green", "195905");
        map.put("Linen", "FAF0E6");
        map.put("Lion", "C19A6B");
        map.put("Liseran Purple", "DE6FA1");
        map.put("Little boy blue", "6CA0DC");
        map.put("Liver", "674C47");
        map.put("Liver (dogs)", "B86D29");
        map.put("Liver (organ)", "6C2E1F");
        map.put("Liver chestnut", "987456");
        map.put("Livid", "6699CC");
        map.put("Lumber", "FFE4CD");
        map.put("Lust", "E62020");
        map.put("Magenta", "FF00FF");
        map.put("Magenta (Crayola)", "FF55A3");
        map.put("Magenta (dye)", "CA1F7B");
        map.put("Magenta (Pantone)", "D0417E");
        map.put("Magenta (process)", "FF0090");
        map.put("Magenta haze", "9F4576");
        map.put("Magenta-pink", "CC338B");
        map.put("Magic mint", "AAF0D1");
        map.put("Magnolia", "F8F4FF");
        map.put("Mahogany", "C04000");
        map.put("Maize", "FBEC5D");
        map.put("Majorelle Blue", "6050DC");
        map.put("Malachite", "0BDA51");
        map.put("Manatee", "979AAA");
        map.put("Mango Tango", "FF8243");
        map.put("Mantis", "74C365");
        map.put("Mardi Gras", "880085");
        map.put("Maroon (Crayola)", "C32148");
        map.put("Maroon (HTML/CSS)", "800000");
        map.put("Maroon (X11)", "B03060");
        map.put("Mauve", "E0B0FF");
        map.put("Mauve taupe", "915F6D");
        map.put("Mauvelous", "EF98AA");
        map.put("May green", "4C9141");
        map.put("Maya blue", "73C2FB");
        map.put("Meat brown", "E5B73B");
        map.put("Medium aquamarine", "66DDAA");
        map.put("Medium blue", "0000CD");
        map.put("Medium candy apple red", "E2062C");
        map.put("Medium carmine", "AF4035");
        map.put("Medium champagne", "F3E5AB");
        map.put("Medium electric blue", "035096");
        map.put("Medium jungle green", "1C352D");
        map.put("Medium lavender magenta", "DDA0DD");
        map.put("Medium orchid", "BA55D3");
        map.put("Medium Persian blue", "0067A5");
        map.put("Medium purple", "9370DB");
        map.put("Medium red-violet", "BB3385");
        map.put("Medium ruby", "AA4069");
        map.put("Medium sea green", "3CB371");
        map.put("Medium sky blue", "80DAEB");
        map.put("Medium slate blue", "7B68EE");
        map.put("Medium spring bud", "C9DC87");
        map.put("Medium spring green", "00FA9A");
        map.put("Medium taupe", "674C47");
        map.put("Medium turquoise", "48D1CC");
        map.put("Medium Tuscan red", "79443B");
        map.put("Medium vermilion", "D9603B");
        map.put("Medium violet-red", "C71585");
        map.put("Mellow apricot", "F8B878");
        map.put("Mellow yellow", "F8DE7E");
        map.put("Melon", "FDBCB4");
        map.put("Metallic Seaweed", "0A7E8C");
        map.put("Metallic Sunburst", "9C7C38");
        map.put("Mexican pink", "E4007C");
        map.put("Midnight blue", "191970");
        map.put("Midnight green (eagle green)", "004953");
        map.put("Mikado yellow", "FFC40C");
        map.put("Mindaro", "E3F988");
        map.put("Ming", "36747D");
        map.put("Mint", "3EB489");
        map.put("Mint cream", "F5FFFA");
        map.put("Mint green", "98FF98");
        map.put("Misty rose", "FFE4E1");
        map.put("Moccasin", "FAEBD7");
        map.put("Mode beige", "967117");
        map.put("Moonstone blue", "73A9C2");
        map.put("Mordant red 19", "AE0C00");
        map.put("Moss green", "8A9A5B");
        map.put("Mountain Meadow", "30BA8F");
        map.put("Mountbatten pink", "997A8D");
        map.put("MSU Green", "18453B");
        map.put("Mughal green", "306030");
        map.put("Mulberry", "C54B8C");
        map.put("Mustard", "FFDB58");
        map.put("Myrtle green", "317873");
        map.put("Nadeshiko pink", "F6ADC6");
        map.put("Napier green", "2A8000");
        map.put("Naples yellow", "FADA5E");
        map.put("Navajo white", "FFDEAD");
        map.put("Navy", "000080");
        map.put("Navy purple", "9457EB");
        map.put("Neon Carrot", "FFA343");
        map.put("Neon fuchsia", "FE4164");
        map.put("Neon green", "39FF14");
        map.put("New Car", "214FC6");
        map.put("New York pink", "D7837F");
        map.put("Non-photo blue", "A4DDED");
        map.put("North Texas Green", "059033");
        map.put("Nyanza", "E9FFDB");
        map.put("Ocean Boat Blue", "0077BE");
        map.put("Ochre", "CC7722");
        map.put("Office green", "008000");
        map.put("Old burgundy", "43302E");
        map.put("Old gold", "CFB53B");
        map.put("Old heliotrope", "563C5C");
        map.put("Old lace", "FDF5E6");
        map.put("Old lavender", "796878");
        map.put("Old mauve", "673147");
        map.put("Old moss green", "867E36");
        map.put("Old rose", "C08081");
        map.put("Old silver", "848482");
        map.put("Olive", "808000");
        map.put("Olive Drab (#3)", "6B8E23");
        map.put("Olive Drab #7", "3C341F");
        map.put("Olivine", "9AB973");
        map.put("Onyx", "353839");
        map.put("Opera mauve", "B784A7");
        map.put("Orange (color wheel)", "FF7F00");
        map.put("Orange (Crayola)", "FF7538");
        map.put("Orange (Pantone)", "FF5800");
        map.put("Orange (RYB)", "FB9902");
        map.put("Orange (web)", "FFA500");
        map.put("Orange peel", "FF9F00");
        map.put("Orange-red", "FF4500");
        map.put("Orchid", "DA70D6");
        map.put("Orchid pink", "F2BDCD");
        map.put("Orioles orange", "FB4F14");
        map.put("Otter brown", "654321");
        map.put("Outer Space", "414A4C");
        map.put("Outrageous Orange", "FF6E4A");
        map.put("Oxford Blue", "002147");
        map.put("OU Crimson Red", "990000");
        map.put("Pakistan green", "006600");
        map.put("Palatinate blue", "273BE2");
        map.put("Palatinate purple", "682860");
        map.put("Pale aqua", "BCD4E6");
        map.put("Pale blue", "AFEEEE");
        map.put("Pale brown", "987654");
        map.put("Pale carmine", "AF4035");
        map.put("Pale cerulean", "9BC4E2");
        map.put("Pale chestnut", "DDADAF");
        map.put("Pale copper", "DA8A67");
        map.put("Pale cornflower blue", "ABCDEF");
        map.put("Pale cyan", "87D3F8");
        map.put("Pale gold", "E6BE8A");
        map.put("Pale goldenrod", "EEE8AA");
        map.put("Pale green", "98FB98");
        map.put("Pale lavender", "DCD0FF");
        map.put("Pale magenta", "F984E5");
        map.put("Pale magenta-pink", "ff99cc");
        map.put("Pale pink", "FADADD");
        map.put("Pale plum", "DDA0DD");
        map.put("Pale red-violet", "DB7093");
        map.put("Pale robin egg blue", "96DED1");
        map.put("Pale silver", "C9C0BB");
        map.put("Pale spring bud", "ECEBBD");
        map.put("Pale taupe", "BC987E");
        map.put("Pale turquoise", "AFEEEE");
        map.put("Pale violet", "CC99FF");
        map.put("Pale violet-red", "DB7093");
        map.put("Pansy purple", "78184A");
        map.put("Paolo Veronese green", "009B7D");
        map.put("Papaya whip", "FFEFD5");
        map.put("Paradise pink", "E63E62");
        map.put("Paris Green", "50C878");
        map.put("Pastel blue", "AEC6CF");
        map.put("Pastel brown", "836953");
        map.put("Pastel gray", "CFCFC4");
        map.put("Pastel green", "77DD77");
        map.put("Pastel magenta", "F49AC2");
        map.put("Pastel orange", "FFB347");
        map.put("Pastel pink", "DEA5A4");
        map.put("Pastel purple", "B39EB5");
        map.put("Pastel red", "FF6961");
        map.put("Pastel violet", "CB99C9");
        map.put("Pastel yellow", "FDFD96");
        map.put("Patriarch", "800080");
        map.put("Payne's grey", "536878");
        map.put("Peach", "FFE5B4");
        map.put("Peach", "FFCBA4");
        map.put("Peach-orange", "FFCC99");
        map.put("Peach puff", "FFDAB9");
        map.put("Peach-yellow", "FADFAD");
        map.put("Pear", "D1E231");
        map.put("Pearl", "EAE0C8");
        map.put("Pearl Aqua", "88D8C0");
        map.put("Pearly purple", "B768A2");
        map.put("Peridot", "E6E200");
        map.put("Periwinkle", "CCCCFF");
        map.put("Persian blue", "1C39BB");
        map.put("Persian green", "00A693");
        map.put("Persian indigo", "32127A");
        map.put("Persian orange", "D99058");
        map.put("Persian pink", "F77FBE");
        map.put("Persian plum", "701C1C");
        map.put("Persian red", "CC3333");
        map.put("Persian rose", "FE28A2");
        map.put("Persimmon", "EC5800");
        map.put("Peru", "CD853F");
        map.put("Phlox", "DF00FF");
        map.put("Phthalo blue", "000F89");
        map.put("Phthalo green", "123524");
        map.put("Picton blue", "45B1E8");
        map.put("Pictorial carmine", "C30B4E");
        map.put("Piggy pink", "FDDDE6");
        map.put("Pine green", "01796F");
        map.put("Pineapple", "563C5C");
        map.put("Pink", "FFC0CB");
        map.put("Pink (Pantone)", "D74894");
        map.put("Pink lace", "FFDDF4");
        map.put("Pink lavender", "D8B2D1");
        map.put("Pink-orange", "FF9966");
        map.put("Pink pearl", "E7ACCF");
        map.put("Pink raspberry", "980036");
        map.put("Pink Sherbet", "F78FA7");
        map.put("Pistachio", "93C572");
        map.put("Platinum", "E5E4E2");
        map.put("Plum", "8E4585");
        map.put("Plum (web)", "DDA0DD");
        map.put("Pomp and Power", "86608E");
        map.put("Popstar", "BE4F62");
        map.put("Portland Orange", "FF5A36");
        map.put("Powder blue", "B0E0E6");
        map.put("Princeton orange", "F58025");
        map.put("Prune", "701C1C");
        map.put("Prussian blue", "003153");
        map.put("Psychedelic purple", "DF00FF");
        map.put("Puce", "CC8899");
        map.put("Puce red", "722F37");
        map.put("Pullman Brown (UPS Brown)", "644117");
        map.put("Pullman Green", "3B331C");
        map.put("Pumpkin", "FF7518");
        map.put("Purple (HTML)", "800080");
        map.put("Purple (Munsell)", "9F00C5");
        map.put("Purple (X11)", "A020F0");
        map.put("Purple Heart", "69359C");
        map.put("Purple mountain majesty", "9678B6");
        map.put("Purple navy", "4E5180");
        map.put("Purple pizzazz", "FE4EDA");
        map.put("Purple taupe", "50404D");
        map.put("Purpureus", "9A4EAE");
        map.put("Quartz", "51484F");
        map.put("Queen blue", "436B95");
        map.put("Queen pink", "E8CCD7");
        map.put("Quinacridone magenta", "8E3A59");
        map.put("Rackley", "5D8AA8");
        map.put("Radical Red", "FF355E");
        map.put("Rajah", "FBAB60");
        map.put("Raspberry", "E30B5D");
        map.put("Raspberry glace", "915F6D");
        map.put("Raspberry pink", "E25098");
        map.put("Raspberry rose", "B3446C");
        map.put("Raw umber", "826644");
        map.put("Razzle dazzle rose", "FF33CC");
        map.put("Razzmatazz", "E3256B");
        map.put("Razzmic Berry", "8D4E85");
        map.put("Rebecca Purple", "663399");
        map.put("Red", "FF0000");
        map.put("Red (Crayola)", "EE204D");
        map.put("Red (Munsell)", "F2003C");
        map.put("Red (NCS)", "C40233");
        map.put("Red (Pantone)", "ED2939");
        map.put("Red (pigment)", "ED1C24");
        map.put("Red (RYB)", "FE2712");
        map.put("Red-brown", "A52A2A");
        map.put("Red devil", "860111");
        map.put("Red-orange", "FF5349");
        map.put("Red-purple", "E40078");
        map.put("Red-violet", "C71585");
        map.put("Redwood", "A45A52");
        map.put("Regalia", "522D80");
        map.put("Registration black", "000000");
        map.put("Resolution blue", "002387");
        map.put("Rhythm", "777696");
        map.put("Rich black", "004040");
        map.put("Rich black (FOGRA29)", "010B13");
        map.put("Rich black (FOGRA39)", "010203");
        map.put("Rich brilliant lavender", "F1A7FE");
        map.put("Rich carmine", "D70040");
        map.put("Rich electric blue", "0892D0");
        map.put("Rich lavender", "A76BCF");
        map.put("Rich lilac", "B666D2");
        map.put("Rich maroon", "B03060");
        map.put("Rifle green", "444C38");
        map.put("Roast coffee", "704241");
        map.put("Robin egg blue", "00CCCC");
        map.put("Rocket metallic", "8A7F80");
        map.put("Roman silver", "838996");
        map.put("Rose", "FF007F");
        map.put("Rose bonbon", "F9429E");
        map.put("Rose ebony", "674846");
        map.put("Rose gold", "B76E79");
        map.put("Rose madder", "E32636");
        map.put("Rose pink", "FF66CC");
        map.put("Rose quartz", "AA98A9");
        map.put("Rose red", "C21E56");
        map.put("Rose taupe", "905D5D");
        map.put("Rose vale", "AB4E52");
        map.put("Rosewood", "65000B");
        map.put("Rosso corsa", "D40000");
        map.put("Rosy brown", "BC8F8F");
        map.put("Royal azure", "0038A8");
        map.put("Royal blue", "002366");
        map.put("Royal blue", "4169E1");
        map.put("Royal fuchsia", "CA2C92");
        map.put("Royal purple", "7851A9");
        map.put("Royal yellow", "FADA5E");
        map.put("Ruber", "CE4676");
        map.put("Rubine red", "D10056");
        map.put("Ruby", "E0115F");
        map.put("Ruby red", "9B111E");
        map.put("Ruddy", "FF0028");
        map.put("Ruddy brown", "BB6528");
        map.put("Ruddy pink", "E18E96");
        map.put("Rufous", "A81C07");
        map.put("Russet", "80461B");
        map.put("Russian green", "679267");
        map.put("Russian violet", "32174D");
        map.put("Rust", "B7410E");
        map.put("Rusty red", "DA2C43");
        map.put("Sacramento State green", "00563F");
        map.put("Saddle brown", "8B4513");
        map.put("Safety orange", "FF7800");
        map.put("Safety orange (blaze orange)", "FF6700");
        map.put("Safety yellow", "EED202");
        map.put("Saffron", "F4C430");
        map.put("Sage", "BCB88A");
        map.put("St. Patrick's blue", "23297A");
        map.put("Salmon", "FA8072");
        map.put("Salmon pink", "FF91A4");
        map.put("Sand", "C2B280");
        map.put("Sand dune", "967117");
        map.put("Sandstorm", "ECD540");
        map.put("Sandy brown", "F4A460");
        map.put("Sandy taupe", "967117");
        map.put("Sangria", "92000A");
        map.put("Sap green", "507D2A");
        map.put("Sapphire", "0F52BA");
        map.put("Sapphire blue", "0067A5");
        map.put("Satin sheen gold", "CBA135");
        map.put("Scarlet", "FF2400");
        map.put("Scarlet", "FD0E35");
        map.put("Schauss pink", "FF91AF");
        map.put("School bus yellow", "FFD800");
        map.put("Screamin' Green", "76FF7A");
        map.put("Sea blue", "006994");
        map.put("Sea green", "2E8B57");
        map.put("Seal brown", "59260B");
        map.put("Seashell", "FFF5EE");
        map.put("Selective yellow", "FFBA00");
        map.put("Sepia", "704214");
        map.put("Shadow", "8A795D");
        map.put("Shadow blue", "778BA5");
        map.put("Shampoo", "FFCFF1");
        map.put("Shamrock green", "009E60");
        map.put("Sheen Green", "8FD400");
        map.put("Shimmering Blush", "D98695");
        map.put("Shocking pink", "FC0FC0");
        map.put("Shocking pink (Crayola)", "FF6FFF");
        map.put("Sienna", "882D17");
        map.put("Silver", "C0C0C0");
        map.put("Silver chalice", "ACACAC");
        map.put("Silver Lake blue", "5D89BA");
        map.put("Silver pink", "C4AEAD");
        map.put("Silver sand", "BFC1C2");
        map.put("Sinopia", "CB410B");
        map.put("Skobeloff", "007474");
        map.put("Sky blue", "87CEEB");
        map.put("Sky magenta", "CF71AF");
        map.put("Slate blue", "6A5ACD");
        map.put("Slate gray", "708090");
        map.put("Smalt (Dark powder blue)", "003399");
        map.put("Smitten", "C84186");
        map.put("Smoke", "738276");
        map.put("Smoky black", "100C08");
        map.put("Smoky Topaz", "933D41");
        map.put("Snow", "FFFAFA");
        map.put("Soap", "CEC8EF");
        map.put("Solid pink", "893843");
        map.put("Sonic silver", "757575");
        map.put("Spartan Crimson", "9E1316");
        map.put("Space cadet", "1D2951");
        map.put("Spanish bistre", "807532");
        map.put("Spanish blue", "0070B8");
        map.put("Spanish carmine", "D10047");
        map.put("Spanish crimson", "E51A4C");
        map.put("Spanish gray", "989898");
        map.put("Spanish green", "009150");
        map.put("Spanish orange", "E86100");
        map.put("Spanish pink", "F7BFBE");
        map.put("Spanish red", "E60026");
        map.put("Spanish sky blue", "00FFFF");
        map.put("Spanish violet", "4C2882");
        map.put("Spanish viridian", "007F5C");
        map.put("Spicy mix", "8B5f4D");
        map.put("Spiro Disco Ball", "0FC0FC");
        map.put("Spring bud", "A7FC00");
        map.put("Spring green", "00FF7F");
        map.put("Star command blue", "007BB8");
        map.put("Steel blue", "4682B4");
        map.put("Steel pink", "CC33CC");
        map.put("Stil de grain yellow", "FADA5E");
        map.put("Stizza", "990000");
        map.put("Stormcloud", "4F666A");
        map.put("Straw", "E4D96F");
        map.put("Strawberry", "FC5A8D");
        map.put("Sunglow", "FFCC33");
        map.put("Sunray", "E3AB57");
        map.put("Sunset", "FAD6A5");
        map.put("Sunset orange", "FD5E53");
        map.put("Super pink", "CF6BA9");
        map.put("Tan", "D2B48C");
        map.put("Tangelo", "F94D00");
        map.put("Tangerine", "F28500");
        map.put("Tangerine yellow", "FFCC00");
        map.put("Tango pink", "E4717A");
        map.put("Taupe", "483C32");
        map.put("Taupe gray", "8B8589");
        map.put("Tea green", "D0F0C0");
        map.put("Tea rose", "F88379");
        map.put("Tea rose", "F4C2C2");
        map.put("Teal", "008080");
        map.put("Teal blue", "367588");
        map.put("Teal deer", "99E6B3");
        map.put("Teal green", "00827F");
        map.put("Telemagenta", "CF3476");
        map.put("Tenné", "CD5700");
        map.put("Terra cotta", "E2725B");
        map.put("Thistle", "D8BFD8");
        map.put("Thulian pink", "DE6FA1");
        map.put("Tickle Me Pink", "FC89AC");
        map.put("Tiffany Blue", "0ABAB5");
        map.put("Tiger's eye", "E08D3C");
        map.put("Timberwolf", "DBD7D2");
        map.put("Titanium yellow", "EEE600");
        map.put("Tomato", "FF6347");
        map.put("Toolbox", "746CC0");
        map.put("Topaz", "FFC87C");
        map.put("Tractor red", "FD0E35");
        map.put("Trolley Grey", "808080");
        map.put("Tropical rain forest", "00755E");
        map.put("True Blue", "0073CF");
        map.put("Tufts Blue", "417DC1");
        map.put("Tulip", "FF878D");
        map.put("Tumbleweed", "DEAA88");
        map.put("Turkish rose", "B57281");
        map.put("Turquoise", "40E0D0");
        map.put("Turquoise blue", "00FFEF");
        map.put("Turquoise green", "A0D6B4");
        map.put("Tuscan", "FAD6A5");
        map.put("Tuscan brown", "6F4E37");
        map.put("Tuscan red", "7C4848");
        map.put("Tuscan tan", "A67B5B");
        map.put("Tuscany", "C09999");
        map.put("Twilight lavender", "8A496B");
        map.put("Tyrian purple", "66023C");
        map.put("UA blue", "0033AA");
        map.put("UA red", "D9004C");
        map.put("Ube", "8878C3");
        map.put("UCLA Blue", "536895");
        map.put("UCLA Gold", "FFB300");
        map.put("UFO Green", "3CD070");
        map.put("Ultramarine", "3F00FF");
        map.put("Ultramarine blue", "4166F5");
        map.put("Ultra pink", "FF6FFF");
        map.put("Ultra red", "FC6C85");
        map.put("Umber", "635147");
        map.put("Unbleached silk", "FFDDCA");
        map.put("United Nations blue", "5B92E5");
        map.put("University of California Gold", "B78727");
        map.put("Unmellow yellow", "FFFF66");
        map.put("UP Forest green", "014421");
        map.put("UP Maroon", "7B1113");
        map.put("Upsdell red", "AE2029");
        map.put("Urobilin", "E1AD21");
        map.put("USAFA blue", "004F98");
        map.put("USC Cardinal", "990000");
        map.put("USC Gold", "FFCC00");
        map.put("University of Tennessee Orange", "F77F00");
        map.put("Utah Crimson", "D3003F");
        map.put("Vanilla", "F3E5AB");
        map.put("Vanilla ice", "F38FA9");
        map.put("Vegas gold", "C5B358");
        map.put("Venetian red", "C80815");
        map.put("Verdigris", "43B3AE");
        map.put("Vermilion", "E34234");
        map.put("Vermilion", "D9381E");
        map.put("Veronica", "A020F0");
        map.put("Very light azure", "74BBFB");
        map.put("Very light blue", "6666FF");
        map.put("Very light malachite green", "64E986");
        map.put("Very light tangelo", "FFB077");
        map.put("Very pale orange", "FFDFBF");
        map.put("Very pale yellow", "FFFFBF");
        map.put("Violet", "8F00FF");
        map.put("Violet (color wheel)", "7F00FF");
        map.put("Violet (RYB)", "8601AF");
        map.put("Violet (web)", "EE82EE");
        map.put("Violet-blue", "324AB2");
        map.put("Violet-red", "F75394");
        map.put("Viridian", "40826D");
        map.put("Viridian green", "009698");
        map.put("Vista blue", "7C9ED9");
        map.put("Vivid amber", "cc9900");
        map.put("Vivid auburn", "922724");
        map.put("Vivid burgundy", "9F1D35");
        map.put("Vivid cerise", "DA1D81");
        map.put("Vivid cerulean", "00aaee");
        map.put("Vivid crimson", "CC0033");
        map.put("Vivid gamboge", "FF9900");
        map.put("Vivid lime green", "a6d608");
        map.put("Vivid malachite", "00cc33");
        map.put("Vivid mulberry", "B80CE3");
        map.put("Vivid orange", "FF5F00");
        map.put("Vivid orange peel", "FFA000");
        map.put("Vivid orchid", "CC00FF");
        map.put("Vivid raspberry", "FF006C");
        map.put("Vivid red", "F70D1A");
        map.put("Vivid red-tangelo", "DF6124");
        map.put("Vivid sky blue", "00CCFF");
        map.put("Vivid tangelo", "F07427");
        map.put("Vivid tangerine", "FFA089");
        map.put("Vivid vermilion", "e56024");
        map.put("Vivid violet", "9F00FF");
        map.put("Vivid yellow", "FFE302");
        map.put("Warm black", "004242");
        map.put("Waterspout", "A4F4F9");
        map.put("Wenge", "645452");
        map.put("Wheat", "F5DEB3");
        map.put("White", "FFFFFF");
        map.put("White smoke", "F5F5F5");
        map.put("Wild blue yonder", "A2ADD0");
        map.put("Wild orchid", "D470A2");
        map.put("Wild Strawberry", "FF43A4");
        map.put("Wild watermelon", "FC6C85");
        map.put("Willpower orange", "FD5800");
        map.put("Windsor tan", "A75502");
        map.put("Wine", "722F37");
        map.put("Wine dregs", "673147");
        map.put("Wisteria", "C9A0DC");
        map.put("Wood brown", "C19A6B");
        map.put("Xanadu", "738678");
        map.put("Yale Blue", "0F4D92");
        map.put("Yankees blue", "1C2841");
        map.put("Yellow", "FFFF00");
        map.put("Yellow (Crayola)", "FCE883");
        map.put("Yellow (Munsell)", "EFCC00");
        map.put("Yellow (NCS)", "FFD300");
        map.put("Yellow (Pantone)", "FEDF00");
        map.put("Yellow (process)", "FFEF00");
        map.put("Yellow (RYB)", "FEFE33");
        map.put("Yellow-green", "9ACD32");
        map.put("Yellow Orange", "FFAE42");
        map.put("Yellow rose", "FFF000");
        map.put("Zaffre", "0014A8");
        map.put("Zinnwaldite brown", "2C1608");
        map.put("Zomp", "39A78E");
    }

    public static Color getColorByName(String string) {
        String hex = map.get(string);
        Color color = new Color(Integer.parseInt(hex, 16));
        return color;
    }

    /**
     * Initialize the color list that we have.
     */
    private ArrayList<ColorName> initColorList() {

        ArrayList<ColorName> colorList = new ArrayList<ColorName>();
        colorList.add(new ColorName("AliceBlue", 0xF0, 0xF8, 0xFF));
        colorList.add(new ColorName("AntiqueWhite", 0xFA, 0xEB, 0xD7));
        colorList.add(new ColorName("Aqua", 0x00, 0xFF, 0xFF));
        colorList.add(new ColorName("Aquamarine", 0x7F, 0xFF, 0xD4));
        colorList.add(new ColorName("Azure", 0xF0, 0xFF, 0xFF));
        colorList.add(new ColorName("Beige", 0xF5, 0xF5, 0xDC));
        colorList.add(new ColorName("Bisque", 0xFF, 0xE4, 0xC4));
        colorList.add(new ColorName("Black", 0x00, 0x00, 0x00));
        colorList.add(new ColorName("BlanchedAlmond", 0xFF, 0xEB, 0xCD));
        colorList.add(new ColorName("Blue", 0x00, 0x00, 0xFF));
        colorList.add(new ColorName("BlueViolet", 0x8A, 0x2B, 0xE2));
        colorList.add(new ColorName("Brown", 0xA5, 0x2A, 0x2A));
        colorList.add(new ColorName("BurlyWood", 0xDE, 0xB8, 0x87));
        colorList.add(new ColorName("CadetBlue", 0x5F, 0x9E, 0xA0));
        colorList.add(new ColorName("Chartreuse", 0x7F, 0xFF, 0x00));
        colorList.add(new ColorName("Chocolate", 0xD2, 0x69, 0x1E));
        colorList.add(new ColorName("Coral", 0xFF, 0x7F, 0x50));
        colorList.add(new ColorName("CornflowerBlue", 0x64, 0x95, 0xED));
        colorList.add(new ColorName("Cornsilk", 0xFF, 0xF8, 0xDC));
        colorList.add(new ColorName("Crimson", 0xDC, 0x14, 0x3C));
        colorList.add(new ColorName("Cyan", 0x00, 0xFF, 0xFF));
        colorList.add(new ColorName("DarkBlue", 0x00, 0x00, 0x8B));
        colorList.add(new ColorName("DarkCyan", 0x00, 0x8B, 0x8B));
        colorList.add(new ColorName("DarkGoldenRod", 0xB8, 0x86, 0x0B));
        colorList.add(new ColorName("DarkGray", 0xA9, 0xA9, 0xA9));
        colorList.add(new ColorName("DarkGreen", 0x00, 0x64, 0x00));
        colorList.add(new ColorName("DarkKhaki", 0xBD, 0xB7, 0x6B));
        colorList.add(new ColorName("DarkMagenta", 0x8B, 0x00, 0x8B));
        colorList.add(new ColorName("DarkOliveGreen", 0x55, 0x6B, 0x2F));
        colorList.add(new ColorName("DarkOrange", 0xFF, 0x8C, 0x00));
        colorList.add(new ColorName("DarkOrchid", 0x99, 0x32, 0xCC));
        colorList.add(new ColorName("DarkRed", 0x8B, 0x00, 0x00));
        colorList.add(new ColorName("DarkSalmon", 0xE9, 0x96, 0x7A));
        colorList.add(new ColorName("DarkSeaGreen", 0x8F, 0xBC, 0x8F));
        colorList.add(new ColorName("DarkSlateBlue", 0x48, 0x3D, 0x8B));
        colorList.add(new ColorName("DarkSlateGray", 0x2F, 0x4F, 0x4F));
        colorList.add(new ColorName("DarkTurquoise", 0x00, 0xCE, 0xD1));
        colorList.add(new ColorName("DarkViolet", 0x94, 0x00, 0xD3));
        colorList.add(new ColorName("DeepPink", 0xFF, 0x14, 0x93));
        colorList.add(new ColorName("DeepSkyBlue", 0x00, 0xBF, 0xFF));
        colorList.add(new ColorName("DimGray", 0x69, 0x69, 0x69));
        colorList.add(new ColorName("DodgerBlue", 0x1E, 0x90, 0xFF));
        colorList.add(new ColorName("FireBrick", 0xB2, 0x22, 0x22));
        colorList.add(new ColorName("FloralWhite", 0xFF, 0xFA, 0xF0));
        colorList.add(new ColorName("ForestGreen", 0x22, 0x8B, 0x22));
        colorList.add(new ColorName("Fuchsia", 0xFF, 0x00, 0xFF));
        colorList.add(new ColorName("Gainsboro", 0xDC, 0xDC, 0xDC));
        colorList.add(new ColorName("GhostWhite", 0xF8, 0xF8, 0xFF));
        colorList.add(new ColorName("Gold", 0xFF, 0xD7, 0x00));
        colorList.add(new ColorName("GoldenRod", 0xDA, 0xA5, 0x20));
        colorList.add(new ColorName("Gray", 0x80, 0x80, 0x80));
        colorList.add(new ColorName("Green", 0x00, 0x80, 0x00));
        colorList.add(new ColorName("GreenYellow", 0xAD, 0xFF, 0x2F));
        colorList.add(new ColorName("HoneyDew", 0xF0, 0xFF, 0xF0));
        colorList.add(new ColorName("HotPink", 0xFF, 0x69, 0xB4));
        colorList.add(new ColorName("IndianRed", 0xCD, 0x5C, 0x5C));
        colorList.add(new ColorName("Indigo", 0x4B, 0x00, 0x82));
        colorList.add(new ColorName("Ivory", 0xFF, 0xFF, 0xF0));
        colorList.add(new ColorName("Khaki", 0xF0, 0xE6, 0x8C));
        colorList.add(new ColorName("Lavender", 0xE6, 0xE6, 0xFA));
        colorList.add(new ColorName("LavenderBlush", 0xFF, 0xF0, 0xF5));
        colorList.add(new ColorName("LawnGreen", 0x7C, 0xFC, 0x00));
        colorList.add(new ColorName("LemonChiffon", 0xFF, 0xFA, 0xCD));
        colorList.add(new ColorName("LightBlue", 0xAD, 0xD8, 0xE6));
        colorList.add(new ColorName("LightCoral", 0xF0, 0x80, 0x80));
        colorList.add(new ColorName("LightCyan", 0xE0, 0xFF, 0xFF));
        colorList.add(new ColorName("LightGoldenRodYellow", 0xFA, 0xFA, 0xD2));
        colorList.add(new ColorName("LightGray", 0xD3, 0xD3, 0xD3));
        colorList.add(new ColorName("LightGreen", 0x90, 0xEE, 0x90));
        colorList.add(new ColorName("LightPink", 0xFF, 0xB6, 0xC1));
        colorList.add(new ColorName("LightSalmon", 0xFF, 0xA0, 0x7A));
        colorList.add(new ColorName("LightSeaGreen", 0x20, 0xB2, 0xAA));
        colorList.add(new ColorName("LightSkyBlue", 0x87, 0xCE, 0xFA));
        colorList.add(new ColorName("LightSlateGray", 0x77, 0x88, 0x99));
        colorList.add(new ColorName("LightSteelBlue", 0xB0, 0xC4, 0xDE));
        colorList.add(new ColorName("LightYellow", 0xFF, 0xFF, 0xE0));
        colorList.add(new ColorName("Lime", 0x00, 0xFF, 0x00));
        colorList.add(new ColorName("LimeGreen", 0x32, 0xCD, 0x32));
        colorList.add(new ColorName("Linen", 0xFA, 0xF0, 0xE6));
        colorList.add(new ColorName("Magenta", 0xFF, 0x00, 0xFF));
        colorList.add(new ColorName("Maroon", 0x80, 0x00, 0x00));
        colorList.add(new ColorName("MediumAquaMarine", 0x66, 0xCD, 0xAA));
        colorList.add(new ColorName("MediumBlue", 0x00, 0x00, 0xCD));
        colorList.add(new ColorName("MediumOrchid", 0xBA, 0x55, 0xD3));
        colorList.add(new ColorName("MediumPurple", 0x93, 0x70, 0xDB));
        colorList.add(new ColorName("MediumSeaGreen", 0x3C, 0xB3, 0x71));
        colorList.add(new ColorName("MediumSlateBlue", 0x7B, 0x68, 0xEE));
        colorList.add(new ColorName("MediumSpringGreen", 0x00, 0xFA, 0x9A));
        colorList.add(new ColorName("MediumTurquoise", 0x48, 0xD1, 0xCC));
        colorList.add(new ColorName("MediumVioletRed", 0xC7, 0x15, 0x85));
        colorList.add(new ColorName("MidnightBlue", 0x19, 0x19, 0x70));
        colorList.add(new ColorName("MintCream", 0xF5, 0xFF, 0xFA));
        colorList.add(new ColorName("MistyRose", 0xFF, 0xE4, 0xE1));
        colorList.add(new ColorName("Moccasin", 0xFF, 0xE4, 0xB5));
        colorList.add(new ColorName("NavajoWhite", 0xFF, 0xDE, 0xAD));
        colorList.add(new ColorName("Navy", 0x00, 0x00, 0x80));
        colorList.add(new ColorName("OldLace", 0xFD, 0xF5, 0xE6));
        colorList.add(new ColorName("Olive", 0x80, 0x80, 0x00));
        colorList.add(new ColorName("OliveDrab", 0x6B, 0x8E, 0x23));
        colorList.add(new ColorName("Orange", 0xFF, 0xA5, 0x00));
        colorList.add(new ColorName("OrangeRed", 0xFF, 0x45, 0x00));
        colorList.add(new ColorName("Orchid", 0xDA, 0x70, 0xD6));
        colorList.add(new ColorName("PaleGoldenRod", 0xEE, 0xE8, 0xAA));
        colorList.add(new ColorName("PaleGreen", 0x98, 0xFB, 0x98));
        colorList.add(new ColorName("PaleTurquoise", 0xAF, 0xEE, 0xEE));
        colorList.add(new ColorName("PaleVioletRed", 0xDB, 0x70, 0x93));
        colorList.add(new ColorName("PapayaWhip", 0xFF, 0xEF, 0xD5));
        colorList.add(new ColorName("PeachPuff", 0xFF, 0xDA, 0xB9));
        colorList.add(new ColorName("Peru", 0xCD, 0x85, 0x3F));
        colorList.add(new ColorName("Pink", 0xFF, 0xC0, 0xCB));
        colorList.add(new ColorName("Plum", 0xDD, 0xA0, 0xDD));
        colorList.add(new ColorName("PowderBlue", 0xB0, 0xE0, 0xE6));
        colorList.add(new ColorName("Purple", 0x80, 0x00, 0x80));
        colorList.add(new ColorName("Red", 0xFF, 0x00, 0x00));
        colorList.add(new ColorName("RosyBrown", 0xBC, 0x8F, 0x8F));
        colorList.add(new ColorName("RoyalBlue", 0x41, 0x69, 0xE1));
        colorList.add(new ColorName("SaddleBrown", 0x8B, 0x45, 0x13));
        colorList.add(new ColorName("Salmon", 0xFA, 0x80, 0x72));
        colorList.add(new ColorName("SandyBrown", 0xF4, 0xA4, 0x60));
        colorList.add(new ColorName("SeaGreen", 0x2E, 0x8B, 0x57));
        colorList.add(new ColorName("SeaShell", 0xFF, 0xF5, 0xEE));
        colorList.add(new ColorName("Sienna", 0xA0, 0x52, 0x2D));
        colorList.add(new ColorName("Silver", 0xC0, 0xC0, 0xC0));
        colorList.add(new ColorName("SkyBlue", 0x87, 0xCE, 0xEB));
        colorList.add(new ColorName("SlateBlue", 0x6A, 0x5A, 0xCD));
        colorList.add(new ColorName("SlateGray", 0x70, 0x80, 0x90));
        colorList.add(new ColorName("Snow", 0xFF, 0xFA, 0xFA));
        colorList.add(new ColorName("SpringGreen", 0x00, 0xFF, 0x7F));
        colorList.add(new ColorName("SteelBlue", 0x46, 0x82, 0xB4));
        colorList.add(new ColorName("Tan", 0xD2, 0xB4, 0x8C));
        colorList.add(new ColorName("Teal", 0x00, 0x80, 0x80));
        colorList.add(new ColorName("Thistle", 0xD8, 0xBF, 0xD8));
        colorList.add(new ColorName("Tomato", 0xFF, 0x63, 0x47));
        colorList.add(new ColorName("Turquoise", 0x40, 0xE0, 0xD0));
        colorList.add(new ColorName("Violet", 0xEE, 0x82, 0xEE));
        colorList.add(new ColorName("Wheat", 0xF5, 0xDE, 0xB3));
        colorList.add(new ColorName("White", 0xFF, 0xFF, 0xFF));
        colorList.add(new ColorName("WhiteSmoke", 0xF5, 0xF5, 0xF5));
        colorList.add(new ColorName("Yellow", 0xFF, 0xFF, 0x00));
        colorList.add(new ColorName("YellowGreen", 0x9A, 0xCD, 0x32));
        return colorList;
    }

    /**
     * Get the closest color name from our list
     *
     * @param r
     * @param g
     * @param b
     * @return
     */
    public String getColorNameFromRgb(int r, int g, int b) {
        ArrayList<ColorName> colorList = initColorList();
        ColorName closestMatch = null;
        int minMSE = Integer.MAX_VALUE;
        int mse;
        for (ColorName c : colorList) {
            mse = c.computeMSE(r, g, b);
            if (mse < minMSE) {
                minMSE = mse;
                closestMatch = c;
            }
        }

        if (closestMatch != null) {
            return closestMatch.getName();
        } else {
            return "No matched color name.";
        }
    }

    /**
     * Convert hexColor to rgb, then call getColorNameFromRgb(r, g, b)
     *
     * @param hexColor
     * @return
     */
    public String getColorNameFromHex(int hexColor) {
        int r = (hexColor & 0xFF0000) >> 16;
        int g = (hexColor & 0xFF00) >> 8;
        int b = (hexColor & 0xFF);
        return getColorNameFromRgb(r, g, b);
    }

    public int colorToHex(Color c) {
        return Integer.decode("0x"
                + Integer.toHexString(c.getRGB()).substring(2));
    }

    public String getColorNameFromColor(Color color) {
        return getColorNameFromRgb(color.getRed(), color.getGreen(),
                color.getBlue());
    }

//    public Color getColorByName(String name) {
//        
//    }
    /**
     * SubClass of ColorUtils. In order to lookup color name
     *
     * @author Xiaoxiao Li
     *
     */
    public class ColorName {

        public int r, g, b;
        public String name;

        public ColorName(String name, int r, int g, int b) {
            this.r = r;
            this.g = g;
            this.b = b;
            this.name = name;
        }

        public int computeMSE(int pixR, int pixG, int pixB) {
            return (int) (((pixR - r) * (pixR - r) + (pixG - g) * (pixG - g) + (pixB - b)
                    * (pixB - b)) / 3);
        }

        public int getR() {
            return r;
        }

        public int getG() {
            return g;
        }

        public int getB() {
            return b;
        }

        public String getName() {
            return name;
        }
    }

    public static void main(String[] args) {
        Color color;
        try {
            Field field = Color.class.getField("red");
            color = (Color) field.get(null);
            System.out.println("Color " + color);
        } catch (Exception e) {
            color = null; // Not defined
        }
    }
}
